name: Publish Python Package

on:
  push:
    branches: [main]

jobs:
  deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version and create tag
        run: |
          # Get the current version from pyproject.toml
          current_version=$(grep '^version = ' pyproject.toml | sed -e 's/version = "//' -e 's/"//')

          # Increment the patch version (e.g., 0.1.0 -> 0.1.1)
          new_version=$(echo $current_version | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')

          # Update pyproject.toml with the new version
          sed -i "s/version = \"$current_version\"/version = \"$new_version\"/" pyproject.toml

          # Commit and tag the new version
          git add pyproject.toml
          git commit -m "chore(release): version $new_version"
          git tag "v$new_version"
          git push
          git push --tags

      - name: Build package
        run: uv build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
